### ISSUE TITLE
Beautify errors

### ISSUE THREAD

**Issue by rodweb** [plFlok/Nyctea-css-beautifier#2]
Doesn't beautify these chunks of code leaving them as is:
```css
.header--h1{color:#fff}
```
```css
p:nth-of-type(n+1){color:#fff}
```
```css
input[type="text"]{color:white}
```
Omits braces of empty selectors making CSS invalid:
```css
table {} /* → table */
```
